- .github/CODEOWNERS
- .github/pull_request_template.md
Problem & Solution 
=======
In order to streamline our work, I have this PR template that will help us write better PR's. [This C5 article](https://blog.carbonfive.com/why-write-good-pull-requests/) does a really good job in explaining why good pull requests are crucial to software development.
I have also added the [`CODEOWNERS`](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) file that will automatically ping the @CruzHacks/2021-engineers whenever there is a PR ready for review.
> Added PR Template & Codeowners File

- .gitignore
- .stylelintrc.js
- src/stylesheets/_responsiveness.scss
- src/stylesheets/_typography.scss
- src/stylesheets/_variables.scss
- src/views/Hero/Hero.scss
- src/views/Hero/index.view.tsx
- src/views/Home/index.view.tsx
Problem
=======
As a user, 
I want to see the title text and description,
So that I am aware of the tentative event dates.
[Link to Asana Ticket](https://app.asana.com/0/1197738625416321/1198219556358095)
Solution
========
In order for the hero to be two columns and responsive, I structured the hero view with a flexbox. 
- Also updated `.stylelintrc.js` so that we can nest more selectors in SCSS. (Not sure if this is the best way; I did it so the linter won't complain)
* added `responsive-font` mixin from 2020's website
* updated hero view
* Check this branch out and start a local server
* Verify that the homepage title and text are visible & responsive
Screenshots:
> Add Homepage Title + Text

- .firebaserc
- .github/workflows/main.yml
- firebase.json
- package.json
- yarn.lock
Problem & Solution 
=======
CI is failing in `main` and will most likely fail in `production` again. Firebase just released an update to their package and I am trying to see if there is an issue since it seems to not be able to find a target when deploying. I added a `target` prop to each specific environment trying to combat this issue.
> Quick Fix for Failing CI

- src/components/PostcardStack/PostcardStack.scss
- src/views/Hero/Hero.scss
- src/views/Home/index.view.tsx
|PR Message|PR #|
|-|-|
|Responsiveness for smaller mobile screens + Add event date|#22|
> [Deploy] November 2

- package.json
- src/components/EmailSubscription/index.view.tsx
- yarn.lock
Problem & Solution 
=======
In order to prevent dependency on external links, we can use [Material Design Icons](https://dev.materialdesignicons.com/getting-started/react) React components. I've used their `Icon` component along with their SVG images of the icons used!
> Email Icons Changes

- .gitignore
- src/components/Button/Button.scss
- src/components/EmailSubscription/EmailSubscription.scss
- src/stylesheets/_variables.scss
- src/views/Hero/Hero.scss
Problem
=======
Let's keep the color scheme dark so it'll be consistent with the design! Found these colors using the [Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en-US) extension on Chrome
> new color scheme to lead into upcoming design

- src/components/Button/Button.scss
- src/components/EmailSubscription/EmailSubscription.scss
- src/components/PostcardStack/PostcardStack.scss
- src/views/Hero/Hero.scss
Problem
=======
As a mobile user, I find circular buttons favorable over elliptical ones
Solution
========
Unset height unit from `vh` so it doesn't shrink one-dimensionally
before:
after:
> fix email button & postcard on mobile

- src/components/Button/index.view.tsx
- src/stylesheets/_variables.scss
- src/views/Home/Home.scss
- src/views/Home/index.view.tsx
Problem
=======
As an organization, 
we want to be MLH compliant
so we can be sponsored by MLH
[Link to Asana Ticket](https://app.asana.com/0/1197738625416321/1199397217488773/f)
Solution
========
Added the code of conduct object to `buttonProps`.
* added code of conduct button a6a383c
1. Checkout branch and start local server
1. Verify that `Our Code of Conduct` button appears & that it takes you to correct link
Screenshots:
> Code of Conduct Button

- src/components/Button/index.view.tsx
- src/stylesheets/_variables.scss
- src/views/Home/Home.scss
- src/views/Home/index.view.tsx
|PR Message|PR#|
|-|-|
|Code of Conduct & Contact Us Button | #89 |
> [Deploy] November 30

- src/views/Home/props/sponsors.js
Problem & Solution
=======
* Updated Sticker Mule link, per Kelly's request on Slack.
> update Sticker Mule link

- src/components/Navbar/Navbar.scss
- src/views/Home/Home.scss
Problem
=======
`EmailSubscription` component was not working because of previous z-index implementations.
Solution
========
Added z-indices to corresponding components using relative positioning.
> quick z-index fix

- src/views/Team/components/Footer/Footer.scss
- src/views/Team/components/Footer/index.view.tsx
Problem & Solution
=======
Arrow was way too big on mobile, so I added responsive div and arrow components in the team view page. 
* fixed arrow size b88bafc
**Before**
> Fixed Team Arrow

- src/views/Home/components/Schedule/index.view.tsx
Problem & Solution
=======
Added new MLH workshops and revised text.
> updated schedule

- src/views/Home/components/Schedule/index.view.tsx
|pr message|pr#|
|-|-|
|updated schedule| (#177)|
> [Deploy] January 15

- src/components/Background/Background.scss
- src/stylesheets/_typography.scss
- src/views/Home/components/Hero/Hero.scss
- src/views/Home/components/Schedule/index.view.tsx
- src/views/Home/components/Schedule/schedule.scss
Problem
=======
What is the problem this work solves, including
[Link to Asana Ticket](https://app.asana.com/1234)
Solution
========
Created border instead of divider class
* Tidy, well formulated commit message
* Another great commit message
* Something else I/we did
Dev-Ops
=======
If you added an ENV variable, please check off that you've updated the following  
1. A setup step / beginning state
2. What to do next
3. Any other instructions
4. Expected behavior
5. Suggestions for testing
Show-n-tell images/animations here
> fixed line overlap

- src/components/Background/Background.scss
- src/stylesheets/_typography.scss
- src/views/Home/components/Hero/Hero.scss
- src/views/Home/components/Schedule/index.view.tsx
- src/views/Home/components/Schedule/schedule.scss
|PR Message|PR#|
|-|-|
|fixed line overlap in schedule & patch background |(#180)|
> [Deploy] January 16

- package.json
- src/views/Home/index.view.tsx
- src/views/Home/props/navbar.js
- src/views/Home/props/organizerForm.js
- yarn.lock
|PR Message | PR # |
|-|-|
|Feature: Adding Functionality to access Organizer Applications| #234 |
|PR Message | PR # |
|-|-|
|Bump stylelint from 13.8.0 to 13.11.0 | #233|
|Bump eslint-plugin-jest from 24.1.3 to 24.1.5 | #232|
|Bump @mdi/js from 5.8.55 to 5.9.55| #186|
> [Deploy] April 2

- src/views/Home/props/organizerForm.js
Problem
=======
CruzHacks has decided to extend the deadline for applications and the website must be updated to reflect these changes.
Solution
========
Updated the button on the landing page that links to the application google form to reflect the new deadline.
* Updated the organizerForm props file to include a more relevant label and updated the description to update the application deadline.
Show-n-tell images/animations here
> Updating deadline for CruzHacks 2022

- src/views/Home/props/organizerForm.js
|PR Message | PR # |
|-|-|
|Updating deadline for CruzHacks 2022| #236 |
> Updating deadline for CruzHacks 2022 (#236)

- package.json
- yarn.lock
|PR Message | PR # |
|-|-|
|PR Message | PR # |
|-|-|
|Bump sass from 1.32.4 to 1.32.8 | #226|
> Bump sass from 1.32.4 to 1.32.8 (#226)

- .github/deploy_request_template.md
- .gitignore
- diff-script.rb
- docs/prod-deploy.md
Problem & Solution 
=======
We were not documenting how prod deploys worked so I've created a document explaining step-by-step for how to do production deploys. I've also added video demos in that document along with adding the ruby script to see which commits are needed to be cherry-picked & added a `prod` PR document.
> Document Prod Deploys

- src/components/EmailSubscription/EmailSubscription.scss
- src/stylesheets/_typography.scss
- src/views/Error/Error.scss
Problem
=======
The email subscription feedback message is super large. 
Solution
========
* Make the font size and letter spacing more reasonable for the feedback message
Dev-Ops
=======
If you added an ENV variable, please check off that you've updated the following  
1. Enter an email and check the feedback message
Before:
After:
> Fix email subscription feedback message font and spacing

- src/views/Home/index.view.tsx
- src/views/Home/props/hero.json
- src/views/Home/props/navbar.js
* Updating 2021 website with Original Content to be Archived
* Removing Application Links, Maintaining 2021 Statistics, Re-Adding 2021 Event Details
> Final Deployment Reverting 2022 Changes

- src/stylesheets/_typography.scss
- src/views/Home/Home.scss
- src/views/Home/index.view.tsx
Problem
=======
What is the problem this work solves, including
[Link to Asana Ticket](https://app.asana.com/1234)
Solution
========
What I/we did to solve this problem
with @pairperson1
* Tidy, well formulated commit message
* Another great commit message
* Something else I/we did
Dev-Ops
=======
If you added an ENV variable, please check off that you've updated the following  
1. A setup step / beginning state
2. What to do next
3. Any other instructions
4. Expected behavior
5. Suggestions for testing
Show-n-tell images/animations here
> removed email subscription, added retrospective devpost link
